<a href="https://colab.research.google.com/github/mtrtrdev/FaissFinderInteger/blob/main/FaissFinderInteger.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Faissのインストール
!pip install faiss-cpu



     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.0/27.0 MB 11.8 MB/s eta 0:00:00
10000
[[7548 5874 4044 1573]
 [8619 2762 2862  417]
 [6059 5596 1617  106]
 [7167 6353 8302 4062]
 [5531 9262 2933 5512]]
[[14.120588 14.428286 14.519493 14.67854 ]
 [14.769968 15.277808 15.82649  15.894089]
 [14.996596 15.646384 15.67143  15.70339 ]
 [13.788441 13.872476 14.549911 14.625786]
 [13.655877 13.713434 13.981209 14.274239]]


In [ ]:
# 必要なライブラリのインポート
import numpy as np  # 数値計算ライブラリのNumPyをインポート
import faiss        # Faissライブラリをインポート

# データの準備
d = 128  # ベクトルの次元数（例：128次元ベクトル）
nb = 10000  # ベクトルの数（例：10000個のベクトル）
np.random.seed(1234)  # 再現性のためのシード設定（乱数の初期化）
xb = np.random.random((nb, d)).astype('float32')  # ランダムなベクトルを生成し、浮動小数点に変換

# 最初の10件のベクトルデータを参照する
first_10_vectors = xb[:10]
print(first_10_vectors)

# インデックスの作成と学習
index = faiss.IndexFlatL2(d)  # L2距離（ユークリッド距離）を使用するフラットインデックスを作成
index.add(xb)  # 生成したベクトルをインデックスに追加
print("インデックスに格納されているベクトルの数:", index.ntotal)  # インデックスに格納されているベクトルの数を表示

# ベクトル検索の実行
nq = 1  # クエリ（検索するベクトル）の数
xq = np.random.random((nq, d)).astype('float32')  # 検索用のクエリベクトルを生成

k = 4  # 上位k個の最近傍ベクトルを検索（例：4個）
D, I = index.search(xq, k)  # 検索を実行し、距離（D）とインデックス（I）を取得

print("検索クエリ:", xq)
print("最近傍ベクトルのインデックス:", I)  # 最近傍ベクトルのインデックスを表示
print("最近傍までの距離:", D)  # 最近傍ベクトルまでの距離を表示


[[0.19151945 0.62210876 0.43772775 ... 0.15139526 0.33517465 0.65755177]
 [0.07334255 0.0550064  0.3231948  ... 0.03816418 0.5655167  0.6588735 ]
 [0.18326636 0.7974113  0.61236745 ... 0.2667407  0.6050111  0.75354373]
 ...
 [0.8112992  0.8727098  0.6659882  ... 0.60382867 0.18178934 0.5190297 ]
 [0.7101533  0.9249804  0.52913165 ... 0.3737508  0.02177226 0.44833776]
 [0.8931148  0.77588123 0.24916132 ... 0.8627962  0.6299704  0.86965317]]
インデックスに格納されているベクトルの数: 10000
検索クエリ: [[0.72088665 0.01826473 0.00362171 0.49580878 0.23780636 0.6242451
  0.19950843 0.30907512 0.9289233  0.08922268 0.527789   0.59448594
  0.75629604 0.6079342  0.2514233  0.8647671  0.46604067 0.35177153
  0.11092298 0.9628028  0.55072993 0.16476883 0.54734164 0.76782435
  0.43037394 0.918433   0.48025915 0.15189426 0.48342177 0.11581858
  0.26167935 0.12354473 0.34102538 0.2424387  0.38881084 0.48775524
  0.45219925 0.6267964  0.36878383 0.15568438 0.3300349  0.23731104
  0.82648325 0.9633443  0.12393757 0.06397816 